### ISSUE TITLE
Catchpoint blog migration

### ISSUE THREAD

**Issue by doffymingozzz** [etsy/terraform-demux#1]
Hi! Sorry for the issue here, can't find any contacts of you.

It’s Gleb from Catchpoint.com.

I've noticed that your website links to our old blog, which we’re currently migrating from a subdomain to the main domain. The reason I’m reaching out is to make sure you won’t have a 404 error on your website.

You have a link to our old blog on the following pages
I wonder if you’d be able to replace it with the new one:
1) https://codeascraft.com/2012/11/09/october-2012-site-performance-report/ -- https://www.catchpoint.com/blog
2) https://codeascraft.com/2012/11/29/measuring-front-end-performance-with-real-users/ -- https://www.catchpoint.com/blog
3) https://codeascraft.com/2012/12/13/mctop-a-tool-for-analyzing-memcache-get-traffic/ -- https://www.catchpoint.com/blog/datadog-integration-catchpoint

Thanks for linking to Catchpoint.com!

Please don’t hesitate to contact me if something comes up v-gkapusto@catchpoint.com!

Best, 
Gleb

**Comment by ericnorris** [comment]
I've let the team that I believe uses Catchpoint know. Please consider finding or establishing an email contact through our contract in the future.
